version: "3.1"
services:
  mysql:
    image: mysql:5.6
    container_name: phpqa-app-example-mysql
    working_dir: /app
    volumes:
      - ./:/app
      - ./tmp/data/mysql_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=my_app
      - MYSQL_USER=my_app
      - MYSQL_PASSWORD=secret
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
      - "3306:3306"
  php-fpm:
    image: webdevops/php-nginx:7.3
    container_name: phpqa-app-example-webserver
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app/webroot
    ports:
      - "80:80"
      - "443:443"
